# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://gitlab.com/mlrep/mldev/-/blob/master/NOTICE.md

image: python:3.6-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - run

# note: this script implies that the same branch exists in mldev
before_script:
  - set -x
  - apt update && apt install -y curl
  - |
      export MLDEV_BRANCH_NAME="${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
      if [ "master" = "${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" ];
      then
        export MLDEV_BRANCH_NAME="develop" ;
      fi
      if [ "master" = "${CI_COMMIT_REF_NAME}" ];
      then
        export MLDEV_BRANCH_NAME="develop" ;
      fi
  # TODO use dev version for now 
  - curl --silent https://gitlab.com/mlrep/mldev/-/raw/${MLDEV_BRANCH_NAME}/install_mldev.sh -o install_mldev.sh && chmod +x ./install_mldev.sh
  - yes | ./install_mldev.sh base && mldev version
  - python3 -m pip install coverage

run:
  stage: run
  script:
    - echo Init ${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_DIR}
    - coverage run -L --source mldev -m mldev.main --config .mldev/config.yaml init -p venv --no-commit -r ${CI_PROJECT_DIR}
    - coverage run -a -L --source mldev -m mldev.main --config .mldev/config.yaml run --no-commit pipeline
    - coverage report
    - mldev run --force-run --no-commit pipeline
  artifacts:
    paths:
      - results/
  only:
    - merge_requests
    - master
